### ISSUE TITLE
Wrong mnemonic name in lesson OK03

### ISSUE THREAD

**Issue by muellermartin** [Chadderz121/bakingpi-www#2]
Currently I'm doing lesson OK03 and at the end of step 3 "A Big Function" some useful mnemonics are suggested to fix the reset of the GPIO pins. Among these suggested mnemonics is the `not` function, but I can't find it in the [instruction set](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0497a/BABIHJGA.html). The solution also uses the mnemonic `MVNS`.
Therefore I would find it more helpful to use `mvns` instead of `not` in the text.

**Comment by Chadderz121** [comment]
Quite right, `mvns` is the ARM bitwise not instruction. I write quite a lot of PowerPC assembly code, which has a `not` pseudo-instruction, which probably explains the mistake. Fixed in 78b3a2ac8f82a433fbebbee48ad690004cb53161.
